--CREATE table SINGER(
--	ID SERIAL primary key,
--	FIRST_NAME VARCHAR(60) not null,
--	LAST_NAME VARCHAR(40) not null,
--	BIRTH_DATE DATE
--	);
--CREATE table ALBUM(
--	ID SERIAL primary key,
--	SINGER_ID INT not null references SINGER(ID),
--	TITLE VARCHAR(100) not null,
--	RELEASE_DATE DATE
--	);
--
--insert into singer (first_name, last_name, birth_date)
--values ('John', 'Mayer', '1977-10-16');
--insert into singer (first_name, last_name, birth_date)
--values ('Eric', 'Clapton', '1945-03-30');
--insert into singer (first_name, last_name, birth_date)
--values ('John', 'Butler', '1975-04-01');
--
--insert into album (singer_id, title, release_date)
--values (1, 'The Search For Everything', '2017-01-20');
--insert into album (singer_id, title, release_date)
--values (1, 'Battle Studies', '2009-11-17');
--insert into album (singer_id, title, release_date)
--values (2, 'From The Cradle', '1994-09-13');